config/routes.rb
AlyssasBlog::Application.routes.draw do
  devise_for :admins

  resources :posts
  resources :comments
  resources :pictures

  get 'oauth/connect'   => 'pictures#connect'
  get 'oauth/callback' => 'pictures#set_token'
  get 'more_images' => 'pictures#more_images'

  root :to => 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
  		 :validatable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts
  has_many :pictures
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :author, :post_id

  validates_presence_of :body, :author

  belongs_to :post
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :caption, :source

  belongs_to :admin
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content

  validates_presence_of :title, :content
  
  belongs_to :admin
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
	end

	def create
		post = Post.find(params[:comment][:post_id])
		comment = post.comments.create(params[:comment])
		if comment.save
			redirect_to post_url(post)
		else
			redirect_to posts_url
		end
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index
		@client = Instagram.client(:access_token => session[:access_token])
		@pictures = @client.user_recent_media
		@pictures.each do |picture|
			Picture.create(caption: picture.caption.text, source: picture.images.thumbnail.url)
		end
	end

	def connect
		redirect_to Instagram.authorize_url(:redirect_uri => oauth_callback_url)
	end

	def set_token
		response = Instagram.get_access_token(params[:code], :redirect_uri => oauth_callback_url)
		session[:access_token] = response.access_token
		redirect_to pictures_url
	end

	def more_images
		@client = Instagram.client(:access_token => session[:access_token])
		next_twenty = @client.user_recent_media(:max_id => params[:last_picture])
		puts params[:last_picture]	
		puts next_twenty
		respond_to do |format|
			format.json {render json: next_twenty}
			format.js {}
			format.html {render action: 'index'}
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.order("created_at DESC")
	end

	def new
		@post = Post.new
		@pictures = Picture.all
	end

	def create
		admin = current_admin
		post = admin.posts.create(params[:post])
		if post.save
			redirect_to posts_url
		else
			redirect_to new_post_url
		end
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@post = Post.last
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlyssasBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
 	<p class="alert"><%= alert %></p>
 <% if current_admin %>
 	<li><%= link_to "Sign out", destroy_admin_session_path, :method => :delete %></li>
 	<li><%= link_to "Create a new post", new_post_url %></li>
 	<li><%= link_to "Tweet Something"%></li>
 	<li><%= link_to "Import Instagram Picture"%></li>
 	<li><%= link_to "Check-In with Instagram", oauth_connect_url %></li>
 <% end %>

<%= yield %>

</body>
</html>

app/views/pictures/index.html.erb
<div class="pictures">
	<% @pictures.each do |media_item| %>
		<form><input type="hidden" value="<%= media_item.id%>"></form>
		<img src="<%= media_item.images.thumbnail.url%>">
	<% end %>
</div>

<button id="load_more_images">Load More Images</button>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<%= link_to "Home Page", root_url%>

<ul>
	<% @posts.each do |post| %>
		<li><a href="/posts/<%=post.id%>"><%= post.title %></a></li>
		<p><%= post.content %></p>
	<% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= form_for @post do |f| %>
	<%= f.text_field :title, :placeholder => "Title"%>
	<br>
	<%= f.text_area  :content, :placeholder => "Post Content" %>
	<br>
	<button id="add_picture_btn">Add a Picture</button>
	<div class="add_picture">
		<% @pictures.each do |picture|%>
			<img src="<%= picture.source %>">
		<% end %>
	</div>
	<%= f.submit "Submit Post" %>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<p><%= @post.content %></p>

<ul>
	<% @post.comments.each do |comment| %>
	<li><%= comment.body %><br>by <%= comment.author%></li>
	<% end %>
</ul>

<%= form_for @comment do |f|%>
<%= f.hidden_field :post_id, :value => @post.id %>
<%= f.text_area :body, :placeholder => "Enter your Comment" %>
<br>
<%= f.text_field :author, :placeholder => "Your Name" %>
<br>
<%= f.submit "Submit your Comment" %>
<% end %>

<ul>
	<li><%= link_to "Archives", posts_url %></li>
	<li><%= link_to "Most Recent Post", root_url %></li>
</ul>

app/views/welcome/index.html.erb
<h1>Index Page</h1>
<%= link_to "Archives", posts_url %>

<p><a href="/posts/<%=@post.id%>"><%= @post.title %></a></p>
<p><%= @post.content %></p>